### ISSUE TITLE
Error installing on Manjaro

### ISSUE THREAD

**Issue by bkarlan** [excess-c64/v1541commander#2]
I received this error message:

`make: *** [src/bin/v1541commander/v1541commander.mk:54: src/bin/v1541commander/qm/v1541commander-de.qm] Error 127
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().`

**Comment by Zirias** [comment]
Crystal ball answer: you might be missing the Qt linguist tools. Find out which package on your distribution provides the `lrelease` tool of Qt5 and install it.

Otherwise, add details:

* Is this the official source from here?
* If so, did you check out a version tag or the latest?
* Most important: This message isn't the actual error. To be sure, build with `make V=1` and paste the entire log here, enclosed like this:

        ```
        # make V=1
        output from
        build
        ```

**Comment by Zirias** [comment]
No feedback for 14 days, closing this with probable cause missing Qt development tools.

If you still have issues, feel free to add comments.

**Comment by bkarlan** [comment]
How can I delete that which I partially installed?

**Comment by Zirias** [comment]
If you can't *build* it, it certainly doesn't *install* anything.
Anyways, `make install` displays the files installed, so you can remove them manually again.
