### ISSUE TITLE
Incorrect .prg icon

### ISSUE THREAD

**Issue by ktuukkan** [excess-c64/v1541commander#3]
After running the setup on Ubuntu 20.04, all `.prg` files are displayed with Lynx icon.

It seems this is because the mime-types are defined so that both Lynx and PRG icons are assigned with `*.prg` pattern.

This could be fixed by simply removing the `*.prg` from the [Lynx mime-type](https://github.com/excess-c64/v1541commander/blob/master/src/bin/v1541commander/mime/v1541commander.xml#L13). If the definition is deliberate and serves a purpose, perhaps the following `magic` rule doesn't match as intended?

**Comment by Zirias** [comment]
This indeed serves a purpose, the CMB DOS only knows a few fixed file types and lynx files will be `PRG` files (they also typically contain some BASIC stub at the beginning). Using a different extension (`.lnx`) is an option on the PC, but not on the C64.

The match is looking for the PETSCII string `LYNX ` in the file, every lynx header starts with it. Unfortunately, because a BASIC stub *can* be present, the offset where to look for this string is given as a range. So, if some other PRG file would contain this magic string somewhere at the beginning, it would be misidentified, but that's pretty unlikely. Maybe your desktop just ignores the match for a magic string? It worked fine for me when I tested it with KDE5/dolphin.

**Comment by Zirias** [comment]
Just tested again and it's still working here:
![image](https://user-images.githubusercontent.com/5891057/206899915-c3b23a9d-93c2-4a64-bd9b-1dc6c95979d9.png)

Could you maybe try to move the mime-type for lynx files to the end of the file and see if that helps for your desktop? Maybe, if it really ignores the magic string, the order for matching globs matters. In this case, it would never show the lynx icon for a `.prg` file, but that would be much more close to "correct"!

**Comment by Zirias** [comment]
@ktuukkan did you test that? If it helps, I'd change the order for the next release.... please let me know, thanks :)

**Comment by ktuukkan** [comment]
Hi @Zirias, sorry I was a bit busy earlier. I just tried moving the Lynx mime-type last and it indeed seems to resolve the problem. However I'm not able to fully verify if Lynx prg's are detected correctly, but at least renaming a .prg to .lnx changes the icon as well. Nevertheless, this works for me as I don't have/use Lynx anyways. Thanks!

**Comment by Zirias** [comment]
Thanks for the info, so this is the sanest fix, closed :)
